import { defineStore } from "pinia";

export const useProductsStore = defineStore({
  id: "productsStore",
  state: () => ({
    products: {
      penneRigateNoodle: {
        sugarAmount: 20,
        productName: "Penne Rigate Nudeln",
        amount: 500,
        model: "Nudeln_Penne.glb",
        meshMode: false,
        rotation: Math.PI/2,
        amountPerPortion: 330,
        category: "noodles",
      },
      fusilliNoodle: {
        sugarAmount: 20,
        productName: "Fusilli Nudeln",
        amount: 500,
        model: "Nudeln_Fusilli.glb",
        meshMode: false,
        rotation: Math.PI/2,
        amountPerPortion: 330,
        category: "noodles",
      },
      spaghettiNoodle: {
        sugarAmount: 17.5,
        productName: "Spaghetti Nudeln",
        amount: 500,
        model: "Nudeln_Spaghetti.glb",
        meshMode: false,
        rotation: Math.PI/2,
        amountPerPortion: 330,
        category: "noodles",
      },
      finishedDishNoodle: {
        sugarAmount: 8.8,
        productName: "Finished Dish",
        amount: 367.2,
        scale: 0.28,
        model: "Nudeln_finishedDish.glb",
        meshMode: false,
        rotation: Math.PI/2,
        amountPerPortion: 125.4,
        category: "noodles",
      },
      monster: {
        sugarAmount: 20,
        productName: "Monster energy",
        amount: 500,
        scale: 0.3,
        rotation: -Math.PI,
        model: "monster.glb",
        meshMode: false,
        amountPerPortion: 330,
        category: "noodles",
      },
      tomatoes: {
        sugarAmount: 20,
        productName: "Tomato 4-pack",
        amount: 500,
        scale: 0.1,
        rotation: -Math.PI,
        model: "tomato_pack.glb",
        meshMode: false,
        amountPerPortion: 0,
        category: "sauces",
      },
      stainedtomato: {
        sugarAmount: 20,
        productName: "Stained Tomatoes",
        amount: 500,
        scale: 0.15,
        rotation: -Math.PI,
        model: "stainedTomato.glb",
        meshMode: false,
        amountPerPortion: 166,
        category: "sauces",
      },
      coke: {
        sugarAmount: 7,
        productName: "Coke",
        scale: 0.4,
        rotation: 0,
        model: "colaglassCenter.glb",
        meshMode: false,
        amount: 150,
        amountPerPortion: 150,
        category: "fruit",
      },
      tomatosauce: {
        sugarAmount: 6.1,
        productName: "Tomatensauce",
        scale: 0.2,
        rotation: 0,
        model: "tomatensauce.glb",
        meshMode: false,
        amount: 400,
        amountPerPortion: 150,
        category: "tomatosauce",
      },
      tomatosauceBolognese: {
        sugarAmount: 5.6,
        productName: "TomatensauceBolognese",
        scale: 0.2,
        rotation: 0,
        model: "tomatensauce_bolognese.glb",
        meshMode: false,
        amount: 400,
        amountPerPortion: 150,
        category: "tomatosauce",
      },
      chips: {
        sugarAmount: 2,
        productName: "Chips",
        scale: 0.4,
        meshMode: false,
        model: "chips.glb",
        amount: 500,
        amountPerPortion: 50,
        category: "bakery",
      },
      pringlesChips: {
        sugarAmount: 2,
        productName: "Pringles Chips",
        scale: 0.4,
        meshMode: false,
        model: "pringles.glb",
        amount: 200,
        amountPerPortion: 50,
        category: "bakery",
      },
      biscuitBox: {
        sugarAmount: 100,
        productName: "Wheat Biscuit Box",
        scale: 0.2,
        meshMode: false,
        model: "biscuits_wheat.glb",
        amount: 500,
        amountPerPortion: 50,
        category: "bakery",
      },
      biscuitsSugarWheat: {
        sugarAmount: 100,
        productName: "Biscuits Sugar Wheat",
        scale: 0.3,
        meshMode: false,
        model: "biscuits_sugarwheat.glb",
        amount: 400,
        amountPerPortion: 50,
        category: "bakery",
      },
      biscuitsChocolate: {
        sugarAmount: 120,
        productName: "Biscuits Chocolate",
        scale: 0.3,
        meshMode: false,
        model: "biscuits_chocolate.glb",
        amount: 400,
        amountPerPortion: 50,
        category: "bakery",
      },
    },
    shelves: [
      {
        name: "Noodles",
        boards: [
          {
            repeat: 2,
            products: [
              "penneRigateNoodle",
              "penneRigateNoodle",
              "penneRigateNoodle",
              "penneRigateNoodle",
              "penneRigateNoodle",
              "penneRigateNoodle",
              "penneRigateNoodle",
            ],
          },
          {
            repeat: 2,
            products: [
              "fusilliNoodle",
              "fusilliNoodle",
              "fusilliNoodle",
              "fusilliNoodle",
              "fusilliNoodle",
              "fusilliNoodle",
              "fusilliNoodle",
            ],
          },
        ],
      },
      {
        name: "Drinks",
        boards: [
          {
            repeat: 2,
            products: [
              "monster",
              "monster",
              "monster",
              "monster",
              "monster",
              "monster",
              "monster",
              "monster",
            ],
          },
          {
            repeat: 2,
            products: [
              "coke",
              "coke",
              "coke",
              "coke",
              "coke",
              "coke",
              "coke",
              "coke",
            ],
          },
        ],
      },
      {
        name: "Noodles",
        boards: [
          {
            repeat: 4,
            products: [
              "spaghettiNoodle",
              "spaghettiNoodle",
              "spaghettiNoodle",
              "spaghettiNoodle",
              "spaghettiNoodle",
              "spaghettiNoodle",
              "spaghettiNoodle",
            ],
          },
        ],
      },
      {
        name: "Drinks",
        boards: [
          {
            repeat: 2,
            products: [
              "monster",
              "monster",
              "monster",
              "monster",
              "monster",
              "monster",
              "monster",
              "monster",
            ],
          },
          {
            repeat: 2,
            products: [
              "coke",
              "coke",
              "coke",
              "coke",
              "coke",
              "coke",
              "coke",
              "coke",
            ],
          },
        ],
      },
      {
        name: "Noodles",
        boards: [
          {
            repeat: 4,
            products: [
              "finishedDishNoodle",
              "finishedDishNoodle",
              "finishedDishNoodle",
              "finishedDishNoodle",
              "finishedDishNoodle",
              "finishedDishNoodle",
              "finishedDishNoodle",
              "finishedDishNoodle",
              "finishedDishNoodle",
            ],
          },
        ],
      },
      {
        name: "Drinks",
        boards: [
          {
            repeat: 2,
            products: [
              "monster",
              "monster",
              "monster",
              "monster",
              "monster",
              "monster",
              "monster",
              "monster",
            ],
          },
          {
            repeat: 2,
            products: [
              "coke",
              "coke",
              "coke",
              "coke",
              "coke",
              "coke",
              "coke",
              "coke",
            ],
          },
        ],
      },
      {
        name: "Sauces",
        boards: [
          {
            repeat: 2,
            products: [
              "tomatosauce",
              "tomatosauce",
              "tomatosauce",
              "tomatosauce",
              "tomatosauce",
              "tomatosauce",
              "tomatosauce",
              "tomatosauce",
            ],
          },
          {
            repeat: 2,
            products: [
              "tomatosauceBolognese",
              "tomatosauceBolognese",
              "tomatosauceBolognese",
              "tomatosauceBolognese",
              "tomatosauceBolognese",
              "tomatosauceBolognese",
              "tomatosauceBolognese",
              "tomatosauceBolognese",
            ],
          },
        ],
      },

      {
        name: "Snack",
        boards: [
          {
            repeat: 2,
            products: [
              "chips",
              "chips",
              "chips",
              "chips",
              "chips",
              "chips",
              "chips",
            ],
          },
          {
            repeat: 2,
            products: [
              "pringlesChips",
              "pringlesChips",
              "pringlesChips",
              "pringlesChips",
              "pringlesChips",
              "pringlesChips",
              "pringlesChips",
              "pringlesChips",
              "pringlesChips",
              "pringlesChips",
            ],
          },
        ],
      },
      {
        name: "Tomatoes",
        boards: [
          {
            repeat: 2,
            products: [
              "tomatoes",
              "tomatoes",
              "tomatoes",
              "tomatoes",
              "tomatoes",
              "tomatoes",
              "tomatoes",
              "tomatoes",
            ],
          },
          {
            repeat: 2,
            products: [
              "stainedtomato",
              "stainedtomato",
              "stainedtomato",
              "stainedtomato",
              "stainedtomato",
              "stainedtomato",
              "stainedtomato",
              "stainedtomato",
              "stainedtomato",
              "stainedtomato",
              "stainedtomato",
              "stainedtomato",
            ],
          },
        ],
      },

      {
        name: "Snack",
        boards: [
          {
            repeat: 2,
            products: [
              "biscuitBox",
              "biscuitBox",
              "biscuitBox",
              "biscuitBox",
              "biscuitBox",
              "biscuitBox",
            ],
          },
          {
            repeat: 1,
            products: [
              "biscuitsSugarWheat",
              "biscuitsSugarWheat",
              "biscuitsSugarWheat",
              "biscuitsSugarWheat",
              "biscuitsSugarWheat",
              "biscuitsSugarWheat",
              "biscuitsSugarWheat",
              "biscuitsSugarWheat",
              "biscuitsSugarWheat",
              "biscuitsSugarWheat",
              "biscuitsSugarWheat",
            ],
          },
          {
            repeat: 1,
            products: [
              "biscuitsChocolate",
              "biscuitsChocolate",
              "biscuitsChocolate",
              "biscuitsChocolate",
              "biscuitsChocolate",
              "biscuitsChocolate",
              "biscuitsChocolate",
              "biscuitsChocolate",
              "biscuitsChocolate",
              "biscuitsChocolate",
              "biscuitsChocolate",
            ],
          },
        ],
      },
    ],
  }),
  getters: {
    getItemsByCategory: (state) => (category: string) => {
      return state.products.filter((item) => item.category === category);
    },
    getAllItems: (state) => () => {
      return state.products;
    },
  },
  actions: {},
});
